#!/bin/bash

if [ "$1" == "" ] ; then 
    echo average_talker filename 
    exit -1
fi

if [ !  -f "$1" ] ; then
    echo file $1 not found
    exit -1
fi
freqfile="phonfreq.txt"

less /fhgfs/bootphon/scratch/gsynnaeve/TIMIT/train_dev_test_split/timit_ABX_train.item|awk '{if($4!~"sil")if($4!~"#"){p[$4]++;tot++}}END{for(i in p)print i,p[i],p[i]/tot}' >$freqfile 
wc "$1"

awk '{if($3>$4)k=$3"\t"$4;else k=$4"\t"$3;m[k]+=$6;n[k]++;N++}END{for (k in m) print k,m[k]/n[k],n[k]}' "$1" |awk 'BEGIN{while(getline<"'"$freqfile"'")fr[$1]=$2}($0!~"sil"){m+=$3;n++;pond=fr[$1]*fr[$2];pm+=$3*pond;totpond+=pond;p[$1]++;p[$2]++}END{print "Corr=",m/n,"N=",n,"pondcorr=",pm/totpond;for(i in p)np++;print "nb phon=",np,"np cont=",np*(np-1)/2}'


