name: ABXpy
channels:
  - coml
  - conda-forge
dependencies:
  - python>=3.6
  - cython>=0.20.1
  - editdistance
  - h5features>=1.3
  - h5py==2.*
  - numpy>=1.8.1
  - numpydoc
  - mock
  - pandas>=0.13.1
  - pip
  - pytables
  - pytest>=2.6
  - pytest-cov
  - pytest-runner
  - scipy>=0.14.0
  - setuptools
  - sphinx_rtd_theme
